# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- ls -l
- set -o pipefail && xcodebuild test -workspace Example/Trackable.xcworkspace -scheme Trackable-Example -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' | xcpretty
- pod lib lint
